"""Presenting: navigation, steps, lifecycle, presenter window, overview, notes, PDF, offline."""
from __future__ import annotations

import re

from playwright.sync_api import sync_playwright

from _common import OUT, Checks, launch, starter

deck = starter()
out = OUT / "presenting"
out.mkdir(parents=True, exist_ok=True)
url = deck.as_uri()
t = Checks("Presenting")

with sync_playwright() as p:
    b = launch(p)
    ctx = b.new_context(viewport={"width": 1600, "height": 900})
    reqs, errs = [], []
    ctx.on("request", lambda r: reqs.append(r.url))
    pg = ctx.new_page()
    pg.on("pageerror", lambda e: errs.append(str(e)))
    pg.on("console", lambda m: errs.append(m.text) if m.type == "error" else None)
    pg.goto(url)
    pg.wait_for_function("document.documentElement.classList.contains('deck-ready')")
    total = pg.evaluate("Deck.total")

    def st(page=pg):
        return page.evaluate("[Deck.index, Deck.step]")

    t.ok("loads its slides", total >= 15, total)
    t.ok("starts on slide 1 and writes the hash", pg.evaluate("location.hash") == "#1")
    scale = pg.evaluate("getComputedStyle(document.documentElement).getPropertyValue('--deck-scale')")
    t.ok("stage scales to fit a 1600x900 window", abs(float(scale) - 1600 / 1920) < 0.001, scale)
    pg.set_viewport_size({"width": 1000, "height": 900})
    pg.wait_for_timeout(50)
    scale = float(pg.evaluate("getComputedStyle(document.documentElement).getPropertyValue('--deck-scale')"))
    r = pg.evaluate("(() => { const r=document.querySelector('.deck').getBoundingClientRect(); return [r.left,r.top,r.width,r.height]; })()")
    t.ok("letterboxed and centered in a tall window", abs(scale - 1000 / 1920) < 0.001 and abs(r[0]) < 1 and abs(r[1] - (900 - r[3]) / 2) < 1, r)
    pg.set_viewport_size({"width": 1600, "height": 900})

    pg.keyboard.press("ArrowRight")
    t.ok("ArrowRight goes to slide 2", st() == [1, 0], st())
    hidden = pg.evaluate("Array.from(Deck.slides[1].querySelectorAll('[data-step]')).map(e=>getComputedStyle(e).visibility)")
    t.ok("steps start hidden", hidden == ["hidden"] * 3, hidden)
    pg.keyboard.press("Space")
    pg.keyboard.press("PageDown")
    t.ok("Space and PageDown reveal steps", st() == [1, 2], st())
    pg.keyboard.press("ArrowRight")
    t.ok("third step", st() == [1, 3])
    pg.keyboard.press("ArrowRight")
    t.ok("then the next slide", st() == [2, 0], st())
    pg.keyboard.press("ArrowLeft")
    t.ok("going back shows the previous slide finished", st() == [1, 3] and pg.evaluate("Deck.slides[1].classList.contains('is-rest')"), st())
    pg.keyboard.press("PageUp")
    t.ok("PageUp steps back", st() == [1, 2], st())
    pg.keyboard.press("End")
    t.ok("End goes to the last slide", st()[0] == total - 1)
    pg.keyboard.press("Home")
    t.ok("Home goes to the first", st()[0] == 0)
    pg.keyboard.press("1")
    pg.keyboard.press("2")
    pg.keyboard.press("Enter")
    t.ok("typing 12 then Enter jumps to slide 12", st()[0] == 11, st())
    t.ok("the hash follows", pg.evaluate("location.hash") == "#12")
    pg.mouse.click(800, 450)
    t.ok("a click advances", st()[0] == 12, st())

    pg.evaluate("window.__ev=[]; ['deck:enter','deck:leave','deck:rest','deck:step'].forEach(t=>document.addEventListener(t,e=>window.__ev.push(t+':'+e.target.dataset.slideNumber)))")
    pg.evaluate("Deck.go(3)")
    pg.keyboard.press("ArrowRight")
    mid = pg.evaluate("document.querySelector('.big-number').textContent")
    pg.wait_for_timeout(2400)
    end = pg.evaluate("document.querySelector('.big-number').textContent")
    ev = pg.evaluate("window.__ev")
    t.ok("enter and leave events fire", "deck:leave:4" in ev and "deck:enter:5" in ev, ev)
    t.ok("count-up ends on the written value", end == "15" and mid != "", (mid, end))
    pg.keyboard.press("ArrowRight")
    pg.keyboard.press("ArrowLeft")
    ev = pg.evaluate("window.__ev")
    t.ok("going back fires deck:rest, not deck:enter", "deck:rest:5" in ev[-3:], ev[-4:])

    wave = pg.evaluate("Deck.slides.findIndex(s => s.id === 'custom-wave')")
    pg.evaluate("(i) => Deck.go(i)", wave)
    pg.wait_for_timeout(300)
    h1 = pg.evaluate("(i) => Deck.slides[i].querySelector('.wave rect').getAttribute('height')", wave)
    pg.wait_for_timeout(300)
    h2 = pg.evaluate("(i) => Deck.slides[i].querySelector('.wave rect').getAttribute('height')", wave)
    t.ok("a custom slide's loop animates", h1 != h2, (h1, h2))
    pg.evaluate("(i) => Deck.go(i)", wave + 1)
    pg.wait_for_timeout(100)
    h3 = pg.evaluate("(i) => Deck.slides[i].querySelector('.wave rect').getAttribute('height')", wave)
    pg.wait_for_timeout(300)
    h4 = pg.evaluate("(i) => Deck.slides[i].querySelector('.wave rect').getAttribute('height')", wave)
    t.ok("the loop stops when the slide is left", h3 == h4, (h3, h4))
    disp = pg.evaluate("(i) => getComputedStyle(Deck.slides[i]).display", wave + 1)
    other = pg.evaluate("getComputedStyle(Deck.slides[0]).display")
    t.ok("scoped CSS applies to its own slide only", disp == "grid" and other == "flex", (disp, other))

    pg.keyboard.press("t")
    t.ok("T switches the variant", pg.evaluate("document.documentElement.dataset.variant") == "dark")
    bg = pg.evaluate("getComputedStyle(Deck.slides[1]).backgroundColor")
    t.ok("dark tokens are applied", bg == "rgb(12, 17, 54)", bg)
    pg.keyboard.press("t")
    pg.keyboard.press("n")
    vis = pg.evaluate("getComputedStyle(document.querySelector('.deck-notes-overlay')).display")
    txt = pg.evaluate("document.querySelector('.deck-notes-body').textContent")
    t.ok("N shows the notes overlay", vis == "block" and len(txt.strip()) > 20, txt[:60])
    pg.keyboard.press("n")
    pg.keyboard.press("b")
    t.ok("B blanks the screen", pg.evaluate("document.documentElement.classList.contains('deck-blanked')"))
    pg.keyboard.press("b")
    t.ok("any key brings it back", not pg.evaluate("document.documentElement.classList.contains('deck-blanked')"))

    bar = "getComputedStyle(document.querySelector('.deck-progress')).display"
    t.ok("the progress bar is off by default", pg.evaluate(bar) == "none", pg.evaluate(bar))
    pg.keyboard.press("l")
    t.ok("L shows the progress bar", pg.evaluate(bar) == "block", pg.evaluate(bar))
    pg.keyboard.press("l")
    t.ok("L hides it again", pg.evaluate(bar) == "none", pg.evaluate(bar))
    src = deck.read_text(encoding="utf-8")
    t.ok("the starter has one deck element", src.count('<main class="deck"') == 1)
    opted = out / "progress-on.html"
    opted.write_text(src.replace('<main class="deck"', '<main class="deck" data-progress="on"', 1), encoding="utf-8")
    octx = b.new_context(viewport={"width": 1600, "height": 900})
    po = octx.new_page()
    po.goto(opted.as_uri())
    po.wait_for_function("document.documentElement.classList.contains('deck-ready')")
    t.ok("a deck with data-progress=on starts with the bar shown", po.evaluate(bar) == "block", po.evaluate(bar))
    octx.close()

    pg.keyboard.press("o")
    pg.wait_for_timeout(100)
    t.ok("O opens the overview", pg.evaluate("document.documentElement.classList.contains('deck-overview')"))
    pg.screenshot(path=str(out / "overview.png"))
    pg.keyboard.press("Home")
    pg.keyboard.press("ArrowRight")
    pg.keyboard.press("ArrowRight")
    pg.keyboard.press("Enter")
    t.ok("picking in the overview jumps to that slide", st()[0] == 2 and not pg.evaluate("document.documentElement.classList.contains('deck-overview')"), st())

    with ctx.expect_page() as pop:
        pg.keyboard.press("s")
    pv = pop.value
    pv.on("pageerror", lambda e: errs.append("presenter: " + str(e)))
    pv.wait_for_function("document.documentElement.classList.contains('deck-ready')")
    pv.wait_for_timeout(1200)
    t.ok("S opens a presenter window", pv.evaluate("Deck.mode") == "presenter")
    t.ok("it picks up the audience position", pv.evaluate("Deck.index") == 2, pv.evaluate("Deck.index"))
    frames = [f for f in pv.frames if f != pv.main_frame]
    t.ok("it has two preview frames", len(frames) == 2, len(frames))
    fi = [f.evaluate("[Deck.mode, Deck.index]") for f in frames]
    t.ok("they show the current and the next slide", fi == [["embed", 2], ["embed", 3]], fi)
    pv.bring_to_front()
    pv.keyboard.press("ArrowRight")
    pv.wait_for_timeout(300)
    t.ok("a key in the presenter window moves the audience window", st()[0] == 3 and pv.evaluate("Deck.index") == 3, (st(), pv.evaluate("Deck.index")))
    pg.bring_to_front()
    pg.keyboard.press("ArrowRight")
    pg.wait_for_timeout(300)
    t.ok("a key in the audience window moves the presenter", pv.evaluate("Deck.index") == 4, pv.evaluate("Deck.index"))
    fi = [f.evaluate("[Deck.index, Deck.slides[Deck.index].classList.contains('is-rest')]") for f in frames]
    t.ok("the next-slide preview is at rest", fi[1] == [5, True] and fi[0][0] == 4, fi)
    notes = pv.evaluate("document.querySelector('.deck-pv-notes').textContent")
    cnt = pv.evaluate("document.querySelector('.deck-pv-count').textContent")
    t.ok("the presenter shows notes and the count", len(notes.strip()) > 20 and cnt == f"5 / {total}", (cnt, notes[:50]))
    pv.wait_for_timeout(1200)
    tm = pv.evaluate("document.querySelector('.deck-pv-timer').textContent")
    t.ok("the timer runs after the first move", tm != "0:00", tm)
    t.ok("the windows report being linked", "Linked" in pv.evaluate("document.querySelector('.deck-pv-status').textContent"))
    pv.keyboard.press("l")
    pv.wait_for_timeout(300)
    t.ok("L in the presenter window shows the audience progress bar", pg.evaluate(bar) == "block", pg.evaluate(bar))
    pv.keyboard.press("l")
    pv.wait_for_timeout(300)
    t.ok("and hides it", pg.evaluate(bar) == "none", pg.evaluate(bar))
    pv.set_viewport_size({"width": 1280, "height": 760})
    pv.wait_for_timeout(400)
    pv.screenshot(path=str(out / "presenter.png"))
    pg.reload()
    pg.wait_for_function("document.documentElement.classList.contains('deck-ready')")
    pg.wait_for_timeout(2600)
    pv.bring_to_front()
    pv.keyboard.press("ArrowRight")
    pv.wait_for_timeout(400)
    t.ok("they relink after the audience window reloads", st()[0] == 5, st())
    pv.close()

    pg.emulate_media(media="print")
    pg.pdf(path=str(out / "slides.pdf"), width="1920px", height="1080px", print_background=True, prefer_css_page_size=True)
    pg.emulate_media(media="screen")
    n = len(re.findall(rb"/Type\s*/Page[^s]", (out / "slides.pdf").read_bytes()))
    t.ok("the PDF has one page per slide", n == total, n)
    pg.evaluate("Deck.printNotes({print:false})")
    rule = pg.evaluate("document.getElementById('deck-print-page').textContent")
    pg.emulate_media(media="print")
    pg.pdf(path=str(out / "notes.pdf"), print_background=True, prefer_css_page_size=True, display_header_footer=True)
    pg.emulate_media(media="screen")
    t.ok("printed notes carry their own header and footer: date, title and page numbers, and nothing bottom left",
         re.search(r'@top-left \{ content: "[^"]*\d[^"]*"', rule) and '@top-center { content: "DynamicDecks starter"' in rule
         and '@bottom-left { content: ""; }' in rule and "counter(page)" in rule, rule)
    try:
        from pypdf import PdfReader
        first = PdfReader(str(out / "notes.pdf")).pages[0].extract_text()
        t.ok("so the browser's own footer, with the file's path, is left out", "file:" not in first and "DynamicDecks starter" in first, first[:200])
    except ImportError:
        print("  skip  pypdf is not installed, so the printed text was not read back")
    pg.evaluate("Deck.endPrintNotes(); Deck.rest(false)")
    n = len(re.findall(rb"/Type\s*/Page[^s]", (out / "notes.pdf").read_bytes()))
    t.ok("the notes PDF has one page per slide", n == total, n)
    t.ok("the deck is intact after printing notes", pg.evaluate("document.querySelectorAll('main.deck > section.slide').length") == total)

    c2 = b.new_context(viewport={"width": 1600, "height": 900}, reduced_motion="reduce")
    p2 = c2.new_page()
    p2.goto(url + "#2")
    p2.wait_for_function("!!window.Deck")
    t.ok("reduced motion is honored", p2.evaluate("document.documentElement.classList.contains('deck-no-motion')") and p2.evaluate("Deck.index") == 1)
    c2.close()

    outside = sorted({u for u in reqs if not u.startswith(("data:", "blob:", "about:")) and u.split("#")[0].split("?")[0] != url})
    t.ok("no network requests", not outside, outside)
    t.ok("no script errors", not errs, errs[:5])
    b.close()

t.done()
